spring.application.name=url-shortener
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

app.jwt.secret=${JWT_SECRET:Cy2pIXWar+ZLwVIR2V/D4pC/vGAvHg8hR4FrgJx8Ruw=}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

app.base-url=${APP_BASE_URL:http://localhost:8080}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

app.cache.short-url-ttl-seconds=${SHORT_URL_CACHE_TTL_SECONDS:3600}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ADMIN
management.metrics.tags.application=${spring.application.name}

app.rate-limit.create.capacity=${RATE_LIMIT_CREATE_CAPACITY:10}
app.rate-limit.create.refill-tokens=${RATE_LIMIT_CREATE_REFILL_TOKENS:10}
app.rate-limit.create.refill-seconds=${RATE_LIMIT_CREATE_REFILL_SECONDS:60}

app.rate-limit.redirect.capacity=${RATE_LIMIT_REDIRECT_CAPACITY:60}
app.rate-limit.redirect.refill-tokens=${RATE_LIMIT_REDIRECT_REFILL_TOKENS:60}
app.rate-limit.redirect.refill-seconds=${RATE_LIMIT_REDIRECT_REFILL_SECONDS:60}

app.rate-limit.auth.capacity=${RATE_LIMIT_AUTH_CAPACITY:5}
app.rate-limit.auth.refill-tokens=${RATE_LIMIT_AUTH_REFILL_TOKENS:5}
app.rate-limit.auth.refill-seconds=${RATE_LIMIT_AUTH_REFILL_SECONDS:60}
