spring.application.name=url-shortener
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

app.jwt.secret=${JWT_SECRET:Cy2pIXWar+ZLwVIR2V/D4pC/vGAvHg8hR4FrgJx8Ruw=}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

app.base-url=${APP_BASE_URL:http://localhost:8080}
