CREATE TABLE short_urls (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code    VARCHAR(20)  NOT NULL,
    original_url  TEXT         NOT NULL,
    user_id       BIGINT       REFERENCES users (id) ON DELETE CASCADE,
    click_count   BIGINT       NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT true,
    expires_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_short_urls_short_code UNIQUE (short_code)
);

CREATE INDEX idx_short_urls_user_id ON short_urls (user_id);
