CREATE TABLE click_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url_id BIGINT       NOT NULL REFERENCES short_urls (id) ON DELETE CASCADE,
    clicked_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    referrer     VARCHAR(2048),
    user_agent   VARCHAR(512),
    ip_address   VARCHAR(45)
);

CREATE INDEX idx_click_events_short_url_id ON click_events (short_url_id);
CREATE INDEX idx_click_events_clicked_at ON click_events (clicked_at);
